application: water-reminder
version: 0-01
runtime: python
api_version: 1

handlers:

# Admin Handlers

- url: /console/static
  static_dir: console/app/view/static  
  
- url: /console.*
  script: console/app/console.py
  login: admin


# Static Handlers
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /images
  static_dir: images
  
- url: /(.*\.(mp3|wav))
  static_files: \1
  upload: (.*\.(mp3|wav))  
  
  
# Request Handlers  

- url: /twilio/.*
  script: twilio.py
  
- url: /
  script: index.py


