application: awkwardbeautyca
version: 0-04
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /i/(img|thumb).*
  script: frontend.py

- url: /
  script: index.py
  
- url: /.*
  script: admin.py
  login: admin
